# Generated by Django 5.0.6 on 2024-07-26 18:42

import ckeditor.fields
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_car_photo_alter_car_car_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Bluetooth', 'Bluetooth'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('ParkAssist', 'ParkAssist'), ('power steering', 'power steering'), ('Backup Camera', 'Backup Camera'), ('Navigation System', 'Navigation System'), ('Sunroof', 'Sunroof'), ('Heated Seats', 'Heated Seats'), ('Leather Seats', 'Leather Seats'), ('Parking Sensors', 'Parking Sensors'), ('Blind Spot Monitoring', 'Blind Spot Monitoring')], max_length=100),
        ),
    ]
