from django.db import models
from datetime import datetime
from ckeditor.fields import RichTextField
from multiselectfield import MultiSelectField

# Create your models here.
class Car(models.Model):


    state_choice = (
        ('AF', 'Afghanistan'),
        ('AL', 'Albanie'),
        ('DZ', 'Algérie'),
        ('AS', 'Samoa américaines'),
        ('AD', 'Andorre'),
        ('AO', 'Angola'),
        ('AI', 'Anguilla'),
        ('AQ', 'Antarctique'),
        ('AG', 'Antigua-et-Barbuda'),
        ('AR', 'Argentine'),
        ('AM', 'Arménie'),
        ('AW', 'Aruba'),
        ('AU', 'Australie'),
        ('AT', 'Autriche'),
        ('AZ', 'Azerbaïdjan'),
        ('BS', 'Bahamas'),
        ('BH', 'Bahreïn'),
        ('BD', 'Bangladesh'),
        ('BB', 'Barbade'),
        ('BY', 'Bélarus'),
        ('BE', 'Belgique'),
        ('BZ', 'Belize'),
        ('BJ', 'Bénin'),
        ('BM', 'Bermudes'),
        ('BT', 'Bhoutan'),
        ('BO', 'Bolivie'),
        ('BA', 'Bosnie-Herzégovine'),
        ('BW', 'Botswana'),
        ('BR', 'Brésil'),
        ('IO', 'Territoire britannique de l\'océan Indien'),
        ('BN', 'Brunei Darussalam'),
        ('BG', 'Bulgarie'),
        ('BF', 'Burkina Faso'),
        ('BI', 'Burundi'),
        ('CV', 'Cap-Vert'),
        ('KH', 'Cambodge'),
        ('CM', 'Cameroun'),
        ('CA', 'Canada'),
        ('KY', 'Îles Caïmans'),
        ('CF', 'République centrafricaine'),
        ('TD', 'Tchad'),
        ('CL', 'Chili'),
        ('CN', 'Chine'),
        ('CX', 'Île Christmas'),
        ('CC', 'Îles Cocos (Keeling)'),
        ('CO', 'Colombie'),
        ('KM', 'Comores'),
        ('CG', 'Congo'),
        ('CD', 'République démocratique du Congo'),
        ('CK', 'Îles Cook'),
        ('CR', 'Costa Rica'),
        ('HR', 'Croatie'),
        ('CU', 'Cuba'),
        ('CW', 'Curaçao'),
        ('CY', 'Chypre'),
        ('CZ', 'République tchèque'),
        ('DK', 'Danemark'),
        ('DJ', 'Djibouti'),
        ('DM', 'Dominique'),
        ('DO', 'République dominicaine'),
        ('EC', 'Équateur'),
        ('EG', 'Égypte'),
        ('SV', 'El Salvador'),
        ('GQ', 'Guinée équatoriale'),
        ('ER', 'Érythrée'),
        ('EE', 'Estonie'),
        ('SZ', 'Eswatini'),
        ('ET', 'Éthiopie'),
        ('FJ', 'Fidji'),
        ('FI', 'Finlande'),
        ('FR', 'France'),
        ('GF', 'Guyane française'),
        ('PF', 'Polynésie française'),
        ('GA', 'Gabon'),
        ('GM', 'Gambie'),
        ('GE', 'Géorgie'),
        ('DE', 'Allemagne'),
        ('GH', 'Ghana'),
        ('GI', 'Gibraltar'),
        ('GR', 'Grèce'),
        ('GL', 'Groenland'),
        ('GD', 'Grenade'),
        ('GP', 'Guadeloupe'),
        ('GU', 'Guam'),
        ('GT', 'Guatemala'),
        ('GG', 'Guernesey'),
        ('GN', 'Guinée'),
        ('GW', 'Guinée-Bissau'),
        ('GY', 'Guyana'),
        ('HT', 'Haïti'),
        ('HN', 'Honduras'),
        ('HK', 'Hong Kong'),
        ('HU', 'Hongrie'),
        ('IS', 'Islande'),
        ('IN', 'Inde'),
        ('ID', 'Indonésie'),
        ('IR', 'Iran'),
        ('IQ', 'Irak'),
        ('IE', 'Irlande'),
        ('IM', 'Île de Man'),
        ('IL', 'Israël'),
        ('IT', 'Italie'),
        ('CI', 'Côte d\'Ivoire'),
        ('JM', 'Jamaïque'),
        ('JP', 'Japon'),
        ('JE', 'Jersey'),
        ('JO', 'Jordanie'),
        ('KZ', 'Kazakhstan'),
        ('KE', 'Kenya'),
        ('KI', 'Kiribati'),
        ('KP', 'Corée du Nord'),
        ('KR', 'Corée du Sud'),
        ('KW', 'Koweït'),
        ('KG', 'Kirghizistan'),
        ('LA', 'Laos'),
        ('LV', 'Lettonie'),
        ('LB', 'Liban'),
        ('LS', 'Lesotho'),
        ('LR', 'Liberia'),
        ('LY', 'Libye'),
        ('LI', 'Liechtenstein'),
        ('LT', 'Lituanie'),
        ('LU', 'Luxembourg'),
        ('MO', 'Macao'),
        ('MG', 'Madagascar'),
        ('MW', 'Malawi'),
        ('MY', 'Malaisie'),
        ('MV', 'Maldives'),
        ('ML', 'Mali'),
        ('MT', 'Malte'),
        ('MH', 'Îles Marshall'),
        ('MQ', 'Martinique'),
        ('MR', 'Mauritanie'),
        ('MU', 'Maurice'),
        ('YT', 'Mayotte'),
        ('MX', 'Mexique'),
        ('FM', 'Micronésie'),
        ('MD', 'Moldavie'),
        ('MC', 'Monaco'),
        ('MN', 'Mongolie'),
        ('ME', 'Monténégro'),
        ('MS', 'Montserrat'),
        ('MA', 'Maroc'),
        ('MZ', 'Mozambique'),
        ('MM', 'Myanmar'),
        ('NA', 'Namibie'),
        ('NR', 'Nauru'),
        ('NP', 'Népal'),
        ('NL', 'Pays-Bas'),
        ('NC', 'Nouvelle-Calédonie'),
        ('NZ', 'Nouvelle-Zélande'),
        ('NI', 'Nicaragua'),
        ('NE', 'Niger'),
        ('NG', 'Nigéria'),
        ('NU', 'Niue'),
        ('NF', 'Île Norfolk'),
        ('MK', 'Macédoine du Nord'),
        ('MP', 'Îles Mariannes du Nord'),
        ('NO', 'Norvège'),
        ('OM', 'Oman'),
        ('PK', 'Pakistan'),
        ('PW', 'Palaos'),
        ('PS', 'Palestine'),
        ('PA', 'Panama'),
        ('PG', 'Papouasie-Nouvelle-Guinée'),
        ('PY', 'Paraguay'),
        ('PE', 'Pérou'),
        ('PH', 'Philippines'),
        ('PN', 'Îles Pitcairn'),
        ('PL', 'Pologne'),
        ('PT', 'Portugal'),
        ('PR', 'Porto Rico'),
        ('QA', 'Qatar'),
        ('RE', 'Réunion'),
        ('RO', 'Roumanie'),
        ('RU', 'Russie'),
        ('RW', 'Rwanda'),
        ('BL', 'Saint-Barthélemy'),
        ('SH', 'Sainte-Hélène'),
        ('KN', 'Saint-Christophe-et-Niévès'),
        ('LC', 'Sainte-Lucie'),
        ('MF', 'Saint-Martin (partie française)'),
        ('PM', 'Saint-Pierre-et-Miquelon'),
        ('VC', 'Saint-Vincent-et-les-Grenadines'),
        ('WS', 'Samoa'),
        ('SM', 'Saint-Marin'),
        ('ST', 'Sao Tomé-et-Principe'),
        ('SA', 'Arabie saoudite'),
        ('SN', 'Sénégal'),
        ('RS', 'Serbie'),
        ('SC', 'Seychelles'),
        ('SL', 'Sierra Leone'),
        ('SG', 'Singapour'),
        ('SX', 'Sint Maarten (partie néerlandaise)'),
        ('SK', 'Slovaquie'),
        ('SI', 'Slovénie'),
        ('SB', 'Îles Salomon'),
        ('SO', 'Somalie'),
        ('ZA', 'Afrique du Sud'),
        ('SS', 'Soudan du Sud'),
        ('ES', 'Espagne'),
        ('LK', 'Sri Lanka'),
        ('SD', 'Soudan'),
        ('SR', 'Suriname'),
        ('SE', 'Suède'),
        ('CH', 'Suisse'),
        ('SY', 'Syrie'),
        ('TW', 'Taïwan'),
        ('TJ', 'Tadjikistan'),
        ('TZ', 'Tanzanie'),
        ('TH', 'Thaïlande'),
        ('TL', 'Timor oriental'),
        ('TG', 'Togo'),
        ('TK', 'Tokelau'),
        ('TO', 'Tonga'),
        ('TT', 'Trinité-et-Tobago'),
        ('TN', 'Tunisie'),
        ('TR', 'Turquie'),
        ('TM', 'Turkménistan'),
        ('TC', 'Îles Turques-et-Caïques'),
        ('TV', 'Tuvalu'),
        ('UG', 'Ouganda'),
        ('UA', 'Ukraine'),
        ('AE', 'Émirats arabes unis'),
        ('GB', 'Royaume-Uni'),
        ('US', 'États-Unis'),
        ('UY', 'Uruguay'),
        ('UZ', 'Ouzbékistan'),
        ('VU', 'Vanuatu'),
        ('VE', 'Venezuela'),
        ('VN', 'Vietnam'),
        ('VG', 'Îles Vierges britanniques'),
        ('VI', 'Îles Vierges américaines'),
        ('WF', 'Wallis-et-Futuna'),
        ('EH', 'Sahara occidental'),
        ('YE', 'Yémen'),
        ('ZM', 'Zambie'),
        ('ZW', 'Zimbabwe'),
    )

    features_choices = (
        ('Cruise Control', 'Cruise Control'),
        ('Audio Interface', 'Audio Interface'),
        ('Bluetooth', 'Bluetooth'),
        ('Airbags', 'Airbags'),
        ('Air Conditioning', 'Air Conditioning'),
        ('Seat Heating', 'Seat Heating'),
        ('ParkAssist', 'ParkAssist'),
        ('power steering', 'power steering'),
        ('Backup Camera', 'Backup Camera'),
        ('Navigation System', 'Navigation System'),
        ('Sunroof', 'Sunroof'),
        ('Heated Seats', 'Heated Seats'),
        ('Leather Seats', 'Leather Seats'),
        ('Parking Sensors', 'Parking Sensors'),
        ('Blind Spot Monitoring', 'Blind Spot Monitoring'),
    )

    door_choices = [
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5'),
    ]

    year_choice =[]
    for r in range(2000, (datetime.now().year+1)):
        year_choice.append((r,r))

        car_title = models.CharField(max_length=255)
        state = models.CharField(choices=state_choice, max_length=100)
        city = models.CharField(max_length=100)
        color = models.CharField(max_length=100)
        modele = models.CharField(max_length=100)
        year = models.IntegerField(('year'),choices=year_choice)
        condition = models.CharField(max_length=100)
        price = models.IntegerField()
        description = RichTextField()
        car_photo = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
        car_photo1 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
        car_photo2 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
        car_photo3 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
        car_photo4 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
        features = MultiSelectField(choices=features_choices , max_length=100)
        body_style = models.CharField(max_length=100)
        engine = models.CharField(max_length=100)
        transmission = models.CharField(max_length=100)
        interior = models.CharField(max_length=100)
        miles = models.IntegerField()
        doors = models.IntegerField(choices=door_choices)
        passengers = models.IntegerField()
        vin_no = models.CharField(max_length=100)
        milage = models.IntegerField()
        fuel_type = models.CharField(max_length=50)
        no_of_owners = models.CharField(max_length=100)
        is_featured = models.BooleanField(default=False)
        created_date = models.DateTimeField(default=datetime.now,blank=True)
        #created_date = models.DateTimeField(auto_now_add=True)


        def __str__(self):
           return self.car_title
